# Generated by Django 4.2.28 on 2026-03-01 14:53

import apps.challenges.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('milestone', models.IntegerField(choices=[(50000, 'Beginner - 50K steps'), (70000, 'Intermediate - 70K steps'), (90000, 'Advanced - 90K steps')], help_text='Total steps required to qualify for payout')),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('1000.00'))])),
                ('total_pool', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total prize pool (sum of all entry fees)', max_digits=12)),
                ('max_participants', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1000)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('invite_code', models.CharField(default=apps.challenges.models.generate_invite_code, help_text='Unique code for joining the challenge', max_length=10, unique=True)),
                ('is_private', models.BooleanField(default=False, help_text='Private challenges require invite code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(default=0, help_text='Total steps accumulated during challenge')),
                ('qualified', models.BooleanField(default=False, help_text='Whether user met the milestone requirement')),
                ('payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final payout amount (calculated at challenge end)', max_digits=10)),
                ('rank', models.IntegerField(blank=True, help_text='Final rank in the challenge', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge')),
            ],
            options={
                'ordering': ['-steps'],
            },
        ),
    ]
