# Generated by Django 4.2.28 on 2026-03-01 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['challenge', '-steps'], name='challenges__challen_36a926_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['user', '-joined_at'], name='challenges__user_id_a6761f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('challenge', 'user')},
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', '-created_at'], name='challenges__status_c48f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['invite_code'], name='challenges__invite__fed66d_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['start_date', 'end_date'], name='challenges__start_d_a588ff_idx'),
        ),
    ]
