# Generated by Django 5.0 on 2026-03-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_chat_phase2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='challengemessage',
            new_name='challenges__challen_053da3_idx',
            old_name='challenges__challen_85a734_idx',
        ),
    ]
