# Generated by Django 5.0 on 2026-03-08 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_rename_challenges__challen_85a734_idx_challenges__challen_053da3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='Auto-unfeature after this datetime.', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured challenges appear at top of lobby with a special badge.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_platform_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public challenges appear in the lobby. Private are invite-only.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='platform_bonus_kes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='KES added by platform on top of user entries to boost the pool.', max_digits=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink')], default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this challenge has been viewed in the lobby.'),
        ),
    ]
