# Generated by Django 5.0 on 2026-03-08 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_featured_until_challenge_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='payout_structure',
            field=models.CharField(choices=[('proportional', 'Proportional'), ('winner_takes_all', 'Winner Takes All'), ('top_3', 'Top 3 Split')], default='proportional', help_text='How winnings are distributed at challenge end.', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='best_day_steps',
            field=models.IntegerField(default=0, help_text='Highest single-day step count during challenge window. Higher = better. Updated on each sync.'),
        ),
        migrations.AddField(
            model_name='participant',
            name='gps_step_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of total steps verified by GPS tracking (0-100). Higher = more trustworthy. Used as Level 1 tiebreaker.'),
        ),
        migrations.AddField(
            model_name='participant',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Longest consecutive days with steps > 0 during challenge. Longer = better. Updated nightly.'),
        ),
        migrations.AddField(
            model_name='participant',
            name='milestone_reached_at',
            field=models.DateTimeField(blank=True, help_text='Exact datetime when participant first hit challenge milestone. Earlier = better tiebreaker. Set by sync_steps task.', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='zero_step_days',
            field=models.IntegerField(default=0, help_text='Days within challenge window where participant recorded 0 steps. Fewer = better (more consistent). Updated nightly.'),
        ),
        migrations.CreateModel(
            name='ChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_steps', models.IntegerField()),
                ('gps_verified_pct', models.FloatField()),
                ('milestone_reached_at', models.DateTimeField(blank=True, null=True)),
                ('zero_step_days', models.IntegerField()),
                ('best_day_steps', models.IntegerField()),
                ('longest_streak', models.IntegerField()),
                ('joined_at', models.DateTimeField()),
                ('tied_with_count', models.IntegerField(default=0, help_text='Number of other participants this user tied with.')),
                ('tiebreaker_level', models.IntegerField(blank=True, help_text='Which tiebreaker level broke the tie (1-7). Null if no tie occurred.', null=True)),
                ('tiebreaker_label', models.CharField(blank=True, help_text='Human-readable explanation of tiebreaker used.', max_length=200)),
                ('qualified', models.BooleanField()),
                ('final_rank', models.IntegerField(blank=True, help_text='Null for proportional challenges (no ranking).', null=True)),
                ('payout_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(choices=[('proportional', 'Proportional'), ('dead_heat', 'Dead Heat Split'), ('tiebreaker', 'Tiebreaker'), ('refund', 'Refund (No Qualifiers)'), ('no_payout', 'Did Not Qualify')], max_length=30)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='challenges.challenge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='challenges.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['challenge', 'final_rank', '-final_steps'],
                'unique_together': {('challenge', 'participant')},
            },
        ),
    ]
