# Generated by Django 5.1.15 on 2026-09-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_challenge_payout_structure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="milestone",
            field=models.IntegerField(
                choices=[
                    (10000, "Starter - 10K steps"),
                    (15000, "Warm-up - 15K steps"),
                    (20000, "Walker - 20K steps"),
                    (25000, "Steady - 25K steps"),
                    (30000, "Active - 30K steps"),
                    (40000, "Strong - 40K steps"),
                    (50000, "Endurance - 50K steps"),
                    (65000, "Power - 65K steps"),
                    (80000, "Athletic - 80K steps"),
                    (100000, "Runner - 100K steps"),
                    (125000, "Advanced Runner - 125K steps"),
                    (150000, "Elite - 150K steps"),
                    (200000, "Pro - 200K steps"),
                    (250000, "Heavyweight - 250K steps"),
                    (300000, "Ultra - 300K steps"),
                ],
                help_text="Total steps required to qualify for payout",
            ),
        ),
    ]
