# Generated by Django 5.1.15 on 2026-09-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_alter_challenge_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reasons', models.JSONField(default=list)),
                ('forfeit_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('held', 'Held for review'), ('released', 'Released'), ('forfeited', 'Forfeited')], db_index=True, default='held', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('resolution', models.JSONField(blank=True, default=dict)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='held_payouts', to='challenges.challenge')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_payout_holds', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='held_payout', to='challenges.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='held_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='chal_hold_status_idx'), models.Index(fields=['user', 'status'], name='chal_hold_user_idx')],
            },
        ),
    ]
