# Generated by Django 5.1.15 on 2026-09-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_held_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
