# Generated by Django 5.1.15 on 2026-09-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_archive'),
        ('challenges', '0010_moderation_hide'),
    ]

    operations = [
    ]
