# Generated by Django 5.1.15 on 2026-09-25 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('anomaly', 'Anomaly (unsupervised)'), ('supervised', 'Supervised')], max_length=16)),
                ('version', models.CharField(max_length=64, unique=True)),
                ('feature_version', models.CharField(max_length=16)),
                ('payload', models.JSONField()),
                ('metrics', models.JSONField(default=dict)),
                ('model_card', models.TextField(blank=True, default='')),
                ('trained_on', models.CharField(default='real', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='riskml_artifact_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('label', models.CharField(choices=[('cheat', 'Cheat'), ('honest', 'Honest'), ('unsure', 'Unsure')], max_length=10)),
                ('source', models.CharField(choices=[('admin_payout_review', 'Admin payout review'), ('admin_flag_action', 'Admin action on an anti-cheat flag'), ('admin_manual', 'Admin labelled the day directly'), ('synthetic', 'Synthetic (tests / evaluation only)')], max_length=24)),
                ('source_ref', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_labels_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_start'],
                'indexes': [models.Index(fields=['source', 'label'], name='riskml_label_src_idx'), models.Index(fields=['user', 'date_start'], name='riskml_label_user_idx')],
                'unique_together': {('user', 'source', 'source_ref', 'date_start', 'date_end')},
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model_version', models.CharField(max_length=64)),
                ('feature_version', models.CharField(max_length=16)),
                ('score', models.FloatField()),
                ('explanations', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-score'],
                'indexes': [models.Index(fields=['user', '-date'], name='riskml_score_user_idx'), models.Index(fields=['date', '-score'], name='riskml_score_date_idx')],
                'unique_together': {('user', 'date', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='UserDayFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feature_version', models.CharField(max_length=16)),
                ('steps', models.IntegerField(default=0)),
                ('in_paid_challenge', models.BooleanField(default=False)),
                ('features', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_day_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'feature_version'], name='riskml_feat_date_idx'), models.Index(fields=['user', '-date'], name='riskml_feat_user_idx')],
                'unique_together': {('user', 'date', 'feature_version')},
            },
        ),
    ]
