# Generated by Django 5.1.15 on 2026-09-29 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('users_ranked', models.PositiveIntegerField(default=0)),
                ('teams_ranked', models.PositiveIntegerField(default=0)),
                ('friends_winners', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('goal_hit', 'Daily goal reached'), ('streak', 'Streak milestone'), ('badge', 'Badge earned'), ('challenge_qualified', 'Challenge milestone reached'), ('weekly_winner', 'Topped the weekly friends ranking')], max_length=24)),
                ('key', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cheer', 'Cheer'), ('fire', 'On fire'), ('strong', 'Strong'), ('clap', 'Well done')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.feedevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('via', models.CharField(default='search', help_text='search | code', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('friend_request', 'Friend request'), ('friend_accepted', 'Friend request accepted'), ('weekly_results', 'Weekly results'), ('reaction', 'Reaction'), ('team_role', 'Team role changed'), ('team_removed', 'Removed from team')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_code', models.CharField(max_length=12, unique=True)),
                ('discoverability', models.CharField(choices=[('everyone', 'Everyone'), ('friends_of_friends', 'Friends of friends'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('share_goal_hits', models.BooleanField(default=True)),
                ('share_streaks', models.BooleanField(default=True)),
                ('share_badges', models.BooleanField(default=True)),
                ('share_challenges', models.BooleanField(default=True)),
                ('show_in_rankings', models.BooleanField(default=True)),
                ('notify_friend_requests', models.BooleanField(default=True)),
                ('notify_weekly_results', models.BooleanField(default=True)),
                ('notify_reactions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_enabled', models.BooleanField(default=True, help_text='Master switch: friends, teams, rankings and feed')),
                ('feed_enabled', models.BooleanField(default=True, help_text='Activity feed and reactions')),
                ('teams_enabled', models.BooleanField(default=True, help_text='Creating and joining teams')),
                ('max_team_members', models.PositiveIntegerField(default=30)),
                ('max_teams_per_user', models.PositiveIntegerField(default=3)),
                ('max_friends', models.PositiveIntegerField(default=300)),
                ('friend_requests_per_day', models.PositiveIntegerField(default=30, help_text='Friend requests one user can send per 24 hours')),
                ('totals_watermark', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social settings',
                'verbose_name_plural': 'Social settings',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_key', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=160)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('invite_only', 'Invite only')], default='public', max_length=12)),
                ('invite_code', models.CharField(max_length=12, unique=True)),
                ('is_disabled', models.BooleanField(default=False, help_text='Hidden and frozen by a moderator')),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=255)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('team', 'Team')], max_length=8)),
                ('reason', models.CharField(choices=[('offensive_name', 'Offensive name or photo'), ('harassment', 'Harassment or bullying'), ('spam', 'Spam or fake account'), ('cheating', 'Suspected cheating'), ('other', 'Something else')], max_length=20)),
                ('details', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Action taken'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_reports_received', to=settings.AUTH_USER_MODEL)),
                ('target_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=8)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='social.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamWeeklyTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('steps', models.PositiveBigIntegerField(default=0)),
                ('members_counted', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Set when the week is finalised', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_totals', to='social.team')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyStepTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('days_counted', models.PositiveSmallIntegerField(default=0)),
                ('friends_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('friends_size', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_step_totals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['blocked'], name='social_bloc_blocked_67400d_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='social_unique_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='social_block_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['user', '-created_at'], name='social_feed_user_id_13f372_idx'),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['-created_at'], name='social_feed_created_e393ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedevent',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'key'), name='social_unique_feed_event'),
        ),
        migrations.AddConstraint(
            model_name='feedreaction',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='social_one_reaction_per_user'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['to_user', 'status', '-created_at'], name='social_frie_to_user_b65c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['from_user', 'status', '-created_at'], name='social_frie_from_us_da5228_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_user'), name='social_one_pending_request_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='social_request_not_self'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='social_unique_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='social_friend_not_self'),
        ),
        migrations.AddIndex(
            model_name='socialnotification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='social_soci_recipie_3ed71e_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['visibility', 'is_disabled', '-member_count'], name='social_team_visibil_e751a3_idx'),
        ),
        migrations.AddIndex(
            model_name='socialreport',
            index=models.Index(fields=['status', '-created_at'], name='social_soci_status_9acb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user'], name='social_team_user_id_d094cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='social_unique_team_member'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('team',), name='social_one_owner_per_team'),
        ),
        migrations.AddIndex(
            model_name='teamweeklytotal',
            index=models.Index(fields=['week_start', '-steps'], name='social_team_week_st_0228c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamweeklytotal',
            constraint=models.UniqueConstraint(fields=('team', 'week_start'), name='social_unique_team_week'),
        ),
        migrations.AddIndex(
            model_name='weeklysteptotal',
            index=models.Index(fields=['week_start', '-steps'], name='social_week_week_st_c78494_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklysteptotal',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='social_unique_user_week'),
        ),
    ]
