release: python manage.py migrate && python manage.py collectstatic --noinput
web: daphne -b 0.0.0.0 -p $PORT step2win.asgi:application
worker: celery -A step2win worker -l info --concurrency=2
beat: celery -A step2win beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
