release: python manage.py migrate && python manage.py collectstatic --noinput
web: gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile - step2win.wsgi
worker: celery -A step2win worker -l info --concurrency=2
beat: celery -A step2win beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
