# Generated by Django 5.0.2 on 2026-03-01 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('total_xp', models.IntegerField(default=0)),
                ('xp_this_week', models.IntegerField(default=0)),
                ('weekly_reset', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User XP',
                'verbose_name_plural': 'User XP',
                'indexes': [models.Index(fields=['user'], name='users_userx_user_id_30a079_idx'), models.Index(fields=['level'], name='users_userx_level_a7b958_idx'), models.Index(fields=['total_xp'], name='users_userx_total_x_7aad57_idx')],
            },
        ),
    ]
