# Generated by Django 5.0 on 2026-03-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_daily_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='best_day_steps',
            field=models.IntegerField(default=0, help_text='Highest single-day step count ever recorded for this user. Updated on each step sync.'),
        ),
        migrations.AddField(
            model_name='user',
            name='best_streak',
            field=models.IntegerField(default=0, help_text='Longest streak the user has ever achieved. Updated nightly. Separate from current_streak.'),
        ),
        migrations.AddField(
            model_name='user',
            name='challenges_joined',
            field=models.IntegerField(default=0, help_text='Total number of challenges the user has entered (paid entry fee). Incremented when user joins a challenge. Used for win rate.'),
        ),
    ]
