# Generated by Django 5.1.15 on 2026-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_social_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Set when the account holder deleted their account (PII anonymised; money records kept). See apps.users.account_deletion.', null=True),
        ),
    ]
