# Generated by Django 5.1.15 on 2026-09-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='network_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
