# Generated by Django 5.1.15 on 2026-09-29 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_enabled', models.BooleanField(default=True, help_text='Master switch for the privacy retention job.')),
                ('sync_payload_days', models.PositiveIntegerField(default=90, help_text='Step sync raw payloads are trimmed to aggregate fields after this many days.')),
                ('legacy_waypoint_days', models.PositiveIntegerField(default=30, help_text='Legacy GPS waypoints (LocationWaypoint) are deleted after this many days.')),
                ('risk_ml_days', models.PositiveIntegerField(default=365, help_text='Shadow risk-model features and scores are deleted after this many days.')),
                ('interval_verification_days', models.PositiveIntegerField(default=365, help_text='Per-interval anti-cheat results (IntervalVerificationResult) are deleted after this many days.')),
                ('password_reset_days', models.PositiveIntegerField(default=30, help_text='Password-reset code rows (with the requesting IP) are deleted after this many days.')),
                ('login_log_days', models.PositiveIntegerField(default=30, help_text='Login attempt / access logs (django-axes: username, IP, user agent) are deleted after this many days.')),
                ('retention_batch_size', models.PositiveIntegerField(default=1000)),
                ('export_link_hours', models.PositiveIntegerField(default=72, help_text='How long a finished export can be downloaded.')),
                ('export_cooldown_hours', models.PositiveIntegerField(default=24, help_text='A user can request one export per this many hours.')),
                ('require_consent_at_registration', models.BooleanField(default=True, help_text="Registration is refused unless the Terms/Privacy and activity-data boxes are ticked. Turn off only if an old app build that can't send them is still in wide use.")),
                ('min_terms_version', models.PositiveIntegerField(default=0)),
                ('min_privacy_version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy settings',
                'verbose_name_plural': 'Privacy settings',
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('terms', 'Terms, Privacy Policy and age 18+'), ('health_data', 'Activity and health data processing'), ('location_walks', 'Location during walks I start')], max_length=32)),
                ('granted', models.BooleanField()),
                ('version', models.CharField(max_length=64)),
                ('document_versions', models.JSONField(blank=True, default=dict)),
                ('text_version', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(choices=[('registration', 'Registration form'), ('social_signup', 'Google / Apple sign-up'), ('reconsent', 'Asked again after a policy change'), ('settings', 'Settings > Privacy'), ('walk_start', 'Before the first walk'), ('admin', 'Recorded by staff'), ('api', 'Other')], default='api', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='privacy_consent_latest_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('running', 'Being prepared'), ('ready', 'Ready to download'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('archive', models.BinaryField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='privacy_export_user_idx')],
            },
        ),
    ]
