# Generated by Django 5.1.15 on 2026-09-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacysettings',
            name='walk_raw_points_days',
            field=models.PositiveIntegerField(blank=True, help_text='Raw GPS points of walks are deleted after this many days (blank = server value).', null=True),
        ),
    ]
