# Generated by Django 5.1.15 on 2026-09-29 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('stats', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('size', models.IntegerField(default=0)),
                ('strong_pairs', models.IntegerField(default=0)),
                ('medium_pairs', models.IntegerField(default=0)),
                ('max_pair_score', models.FloatField(default=0.0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-size', 'key'],
            },
        ),
        migrations.CreateModel(
            name='LinkageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holds_enabled', models.BooleanField(default=True)),
                ('same_challenge_hold', models.BooleanField(default=True)),
                ('strong_link_paid_hold', models.BooleanField(default=True)),
                ('paid_lookback_days', models.IntegerField(default=180)),
                ('behaviour_lookback_days', models.IntegerField(default=14)),
                ('medium_link_threshold', models.FloatField(default=1.0)),
                ('network_max_accounts', models.IntegerField(default=6)),
                ('colocation_max_accounts', models.IntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='linkage.linkcluster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_marks_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_marks_revoked', to=settings.AUTH_USER_MODEL)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_marks_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_marks_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_a', 'user_b')},
            },
        ),
        migrations.CreateModel(
            name='LinkEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('shared_device', 'Same phone'), ('shared_payout_account', 'Same payout number or account'), ('shared_deposit_number', 'Same deposit number'), ('phone_sequence', 'Near-sequential phone numbers'), ('shared_network', 'Same home network'), ('co_location', 'Walked at the same place and time'), ('twin_curves', 'Near-identical hourly steps'), ('joint_challenges', 'Join and qualify in the same challenges'), ('handover', 'Steps alternate between the accounts')], max_length=32)),
                ('strength', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak')], max_length=8)),
                ('weight', models.FloatField()),
                ('evidence', models.JSONField(default=dict)),
                ('evidence_first_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_last_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_edges_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_edges_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_a_id', 'user_b_id', 'edge_type'],
                'indexes': [models.Index(fields=['user_a', 'active'], name='linkage_edge_a_idx'), models.Index(fields=['user_b', 'active'], name='linkage_edge_b_idx'), models.Index(fields=['edge_type', 'active'], name='linkage_edge_type_idx')],
                'unique_together': {('user_a', 'user_b', 'edge_type')},
            },
        ),
    ]
