# Generated by Django 5.1.15 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkagesettings',
            name='business_number_min_accounts',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='linkagesettings',
            name='strong_link_paid_includes_payout_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkedge',
            name='edge_type',
            field=models.CharField(choices=[('shared_device', 'Same phone'), ('shared_payout_account', 'Same payout number or account'), ('shared_deposit_number', 'Same deposit number'), ('shared_business_number', 'Shared business number'), ('phone_sequence', 'Near-sequential phone numbers'), ('shared_network', 'Same home network'), ('co_location', 'Walked at the same place and time'), ('twin_curves', 'Near-identical hourly steps'), ('joint_challenges', 'Join and qualify in the same challenges'), ('handover', 'Steps alternate between the accounts')], max_length=32),
        ),
    ]
