# Generated by Django 4.2.28 on 2026-03-01 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('source', models.CharField(choices=[('google_fit', 'Google Fit'), ('apple_health', 'Apple Health'), ('manual', 'Manual Entry')], default='google_fit', max_length=20)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flagged for unusual activity')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw data from health platform', null=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Steps',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StepGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(50000)])),
                ('weekly_goal', models.IntegerField(default=70000, validators=[django.core.validators.MinValueValidator(7000), django.core.validators.MaxValueValidator(350000)])),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('exceeds_cap', 'Exceeds Daily Cap'), ('spike_detected', 'Unusual Spike'), ('impossible_increase', 'Impossible Increase'), ('pattern_anomaly', 'Pattern Anomaly'), ('multiple_devices', 'Multiple Devices')], max_length=50)),
                ('description', models.TextField()),
                ('steps_submitted', models.IntegerField()),
                ('expected_range_min', models.IntegerField(blank=True, null=True)),
                ('expected_range_max', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('action_taken', models.CharField(blank=True, choices=[('none', 'No Action'), ('warning', 'Warning Issued'), ('steps_adjusted', 'Steps Adjusted'), ('account_suspended', 'Account Suspended')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suspicious Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
