# Generated by Django 4.2.28 on 2026-03-01 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stepgoal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysteps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['user', '-created_at'], name='steps_suspi_user_id_f33f25_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['reviewed', '-created_at'], name='steps_suspi_reviewe_ebc656_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysteps',
            index=models.Index(fields=['user', '-date'], name='steps_daily_user_id_aa212a_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysteps',
            index=models.Index(fields=['date'], name='steps_daily_date_9a1eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysteps',
            index=models.Index(fields=['is_suspicious'], name='steps_daily_is_susp_c41661_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysteps',
            unique_together={('user', 'date')},
        ),
    ]
