# Generated by Django 4.2.28 on 2026-03-02 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steps', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('google_fit', 'Google Fit'), ('apple_health', 'Apple Health'), ('manual', 'Manual Entry')], default='google_fit', max_length=20)),
                ('steps', models.IntegerField(default=0)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('calories_active', models.IntegerField(blank=True, null=True)),
                ('active_minutes', models.IntegerField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailysteps',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailysteps',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stepgoal',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='suspiciousactivity',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='suspiciousactivity',
            name='steps_suspi_user_id_f33f25_idx',
        ),
        migrations.RemoveIndex(
            model_name='suspiciousactivity',
            name='steps_suspi_reviewe_ebc656_idx',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='expected_range_max',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='expected_range_min',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='reviewer_notes',
        ),
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DailySteps',
        ),
        migrations.DeleteModel(
            name='StepGoal',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['user', '-date'], name='steps_healt_user_id_fda0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['user', 'date'], name='steps_healt_user_id_26bb59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='healthrecord',
            unique_together={('user', 'date')},
        ),
    ]
