# Generated by Django 5.0.2 on 2026-03-07 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_healthrecord_alter_dailysteps_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('flags_total', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low — Log Only'), ('medium', 'Medium — Admin Review'), ('high', 'High — Auto Cap Steps'), ('critical', 'Critical — Reject Submission')], max_length=10)),
                ('date', models.DateField()),
                ('details', models.JSONField(default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('actioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='steps_fraud_user_id_876506_idx'), models.Index(fields=['reviewed', 'severity', '-created_at'], name='steps_fraud_reviewe_d05a46_idx')],
            },
        ),
    ]
