# Generated by Django 5.0 on 2026-03-08 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_trustscore_fraudflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyStepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField()),
                ('steps', models.IntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('calories', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'hour'],
                'indexes': [models.Index(fields=['user', 'date'], name='steps_hourl_user_id_382802_idx')],
                'unique_together': {('user', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='LocationWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_m', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_waypoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'recorded_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='steps_locat_user_id_d16d2b_idx')],
            },
        ),
    ]
