# Generated by Django 5.1.15 on 2026-05-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_security_hardening'),
        ('steps', '0007_interval_daily_verification_storage'),
    ]

    operations = [
    ]
