# Generated by Django 5.1.15 on 2026-06-16 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0008_merge_20260502_1107"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deviceregistration",
            name="device_registration_unique",
        ),
        migrations.RemoveConstraint(
            model_name="stepsession",
            name="session_unique_token_hash",
        ),
        migrations.AlterField(
            model_name="stepsyncevent",
            name="replay_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="deviceregistration",
            unique_together={("user", "device_id")},
        ),
        migrations.AlterUniqueTogether(
            name="stepsyncevent",
            unique_together={("user", "client_event_id")},
        ),
        migrations.AddIndex(
            model_name="deviceregistration",
            index=models.Index(
                fields=["device_id"], name="steps_devic_device__16e427_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stepsyncevent",
            index=models.Index(
                fields=["replay_detected"], name="steps_steps_replay__6bf624_idx"
            ),
        ),
    ]
