# Generated by Django 5.1.15 on 2026-07-19 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0008_merge_20260502_1107"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deviceregistration",
            name="device_registration_unique",
        ),
        migrations.RemoveConstraint(
            model_name="stepsession",
            name="session_unique_token_hash",
        ),
        migrations.RemoveConstraint(
            model_name="stepsyncevent",
            name="syncevent_unique_user_event",
        ),
        migrations.RenameIndex(
            model_name="deviceregistration",
            new_name="steps_devic_user_id_ae956a_idx",
            old_name="device_reg_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="stepsession",
            new_name="steps_steps_user_id_fe7d80_idx",
            old_name="session_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stepsession",
            new_name="steps_steps_user_id_502435_idx",
            old_name="session_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="stepsession",
            new_name="steps_steps_expires_b2762c_idx",
            old_name="session_expiry_status_idx",
        ),
        migrations.RenameIndex(
            model_name="stepsyncevent",
            new_name="steps_steps_session_07bd06_idx",
            old_name="syncevent_session_sq_idx",
        ),
        migrations.RenameIndex(
            model_name="stepsyncevent",
            new_name="steps_steps_user_id_35a32d_idx",
            old_name="syncevent_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="stepsyncevent",
            new_name="steps_steps_payload_ce435b_idx",
            old_name="syncevent_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="suspicioussessionreview",
            new_name="steps_suspi_status_83e963_idx",
            old_name="review_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="suspicioussessionreview",
            new_name="steps_suspi_user_id_dd70f6_idx",
            old_name="review_user_created_idx",
        ),
        migrations.AlterField(
            model_name="stepsyncevent",
            name="replay_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="deviceregistration",
            unique_together={("user", "device_id")},
        ),
        migrations.AlterUniqueTogether(
            name="stepsyncevent",
            unique_together={("user", "client_event_id")},
        ),
        migrations.AddIndex(
            model_name="deviceregistration",
            index=models.Index(
                fields=["device_id"], name="steps_devic_device__16e427_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stepsyncevent",
            index=models.Index(
                fields=["replay_detected"], name="steps_steps_replay__6bf624_idx"
            ),
        ),
    ]
