# Generated by Django 5.1.15 on 2026-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0009_rename_device_reg_user_active_idx_steps_devic_user_id_ae956a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='last_client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
