# Generated by Django 5.1.15 on 2026-09-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0010_healthrecord_last_client_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustscore',
            name='admin_ceiling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trustscore',
            name='admin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trustscore',
            name='admin_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='trustscore',
            name='last_recovered_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
