# Generated by Django 5.1.15 on 2026-09-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0011_trustscore_admin_lock_and_daily_recovery'),
        ('steps', '0012_redact_sync_event_session_tokens'),
    ]

    operations = [
    ]
