# Generated by Django 5.1.15 on 2026-09-29 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0013_merge_anticheat_phase0_trustscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='eligible_steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='tier_grandfathered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='tier_sensor_verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='tier_unverified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='tier_walk_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='tier_wearable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stepsession',
            name='install_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stepsession',
            name='integrity_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepsession',
            name='integrity_status',
            field=models.CharField(default='unchecked', max_length=16),
        ),
        migrations.AddField(
            model_name='stepsession',
            name='integrity_verdict',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stepsession',
            name='tz_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stepsession',
            name='tz_offset_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WalkPrivacyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=64)),
                ('precision', models.PositiveSmallIntegerField(default=7)),
                ('radius_m', models.PositiveIntegerField(default=300)),
                ('cell_hashes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='walk_privacy_zone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_walk_id', models.CharField(blank=True, default='', max_length=64)),
                ('platform', models.CharField(blank=True, default='', max_length=12)),
                ('install_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('unverified', 'Unverified')], default='pending', max_length=12)),
                ('verdict_reasons', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('local_date', models.DateField(db_index=True)),
                ('tz_offset_minutes', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(default=0)),
                ('verified_steps', models.IntegerField(default=0)),
                ('gait_verified_steps', models.IntegerField(default=0)),
                ('gait_shake_steps', models.IntegerField(default=0)),
                ('gait_unknown_steps', models.IntegerField(default=0)),
                ('step_source', models.CharField(blank=True, default='', max_length=24)),
                ('distance_m', models.FloatField(default=0.0)),
                ('duration_s', models.IntegerField(default=0)),
                ('avg_speed_mps', models.FloatField(default=0.0)),
                ('max_speed_mps', models.FloatField(default=0.0)),
                ('vehicle_seconds', models.IntegerField(default=0)),
                ('vehicle_hours', models.JSONField(blank=True, default=list)),
                ('mock_location', models.BooleanField(default=False)),
                ('auto_ended', models.BooleanField(default=False)),
                ('points_count', models.IntegerField(default=0)),
                ('raw_points', models.JSONField(blank=True, default=list)),
                ('raw_points_purged_at', models.DateTimeField(blank=True, null=True)),
                ('simplified_polyline', models.TextField(blank=True, default='')),
                ('integrity_nonce', models.CharField(blank=True, default='', max_length=64)),
                ('integrity_status', models.CharField(default='unchecked', max_length=16)),
                ('integrity_verdict', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='steps.deviceregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'local_date'], name='steps_walk_user_day_idx'), models.Index(fields=['user', '-started_at'], name='steps_walk_user_start_idx'), models.Index(fields=['status', 'ended_at'], name='steps_walk_status_end_idx')],
            },
        ),
    ]
