# Generated by Django 5.1.15 on 2026-09-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_update_withdrawal_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='wallet.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('challenge_entry', 'Challenge Entry'), ('payout', 'Payout'), ('fee', 'Platform Fee'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=20),
        ),
    ]
