# Generated by Django 5.0.2 on 2026-03-07 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee percentage on challenge pools', max_digits=5)),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum amount users can withdraw', max_digits=10)),
                ('withdrawal_processing_time', models.IntegerField(default=24, help_text='Expected withdrawal processing time in hours')),
                ('min_challenge_entry_fee', models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum entry fee for challenges', max_digits=10)),
                ('max_challenge_entry_fee', models.DecimalField(decimal_places=2, default=1000.0, help_text='Maximum entry fee for challenges', max_digits=10)),
                ('min_challenge_milestone', models.IntegerField(default=1000, help_text='Minimum steps milestone for challenges')),
                ('max_challenge_milestone', models.IntegerField(default=100000, help_text='Maximum steps milestone for challenges')),
                ('max_challenge_participants', models.IntegerField(default=100, help_text='Maximum participants per challenge')),
                ('challenge_approval_required', models.BooleanField(default=True, help_text='Whether challenges require admin approval')),
                ('registrations_enabled', models.BooleanField(default=True, help_text='Allow new user registrations')),
                ('challenges_enabled', models.BooleanField(default=True, help_text='Allow challenge creation')),
                ('withdrawals_enabled', models.BooleanField(default=True, help_text='Allow withdrawal requests')),
                ('referral_program_enabled', models.BooleanField(default=True, help_text='Enable referral program')),
                ('xp_per_step', models.DecimalField(decimal_places=2, default=0.1, help_text='XP awarded per step taken', max_digits=5)),
                ('daily_goal_bonus_xp', models.IntegerField(default=100, help_text='Bonus XP for reaching daily step goal')),
                ('admin_email', models.EmailField(default='admin@step2win.com', help_text='Admin contact email', max_length=254)),
                ('support_email', models.EmailField(default='support@step2win.com', help_text='Support contact email', max_length=254)),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (blocks all user access)')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
