# Generated by Django 5.0.2 on 2026-03-07 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('ban', 'Ban'), ('unban', 'Unban'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('promote', 'Promote'), ('demote', 'Demote'), ('reset_password', 'Reset Password'), ('settings_change', 'Settings Change')], max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('challenge', 'Challenge'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('badge', 'Badge'), ('settings', 'System Settings'), ('auth', 'Authentication')], max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='admin_api_a_created_b8d9ec_idx'), models.Index(fields=['admin', '-created_at'], name='admin_api_a_admin_i_fb836c_idx'), models.Index(fields=['resource_type', '-created_at'], name='admin_api_a_resourc_130053_idx'), models.Index(fields=['action', '-created_at'], name='admin_api_a_action_9da028_idx')],
            },
        ),
    ]
