# Generated by Django 5.1.15 on 2026-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0003_alter_auditlog_resource_type_supportticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="challenge_milestones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered milestone options exposed to the customer app",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="max_challenge_milestone",
            field=models.IntegerField(
                default=300000, help_text="Maximum steps milestone for challenges"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="min_challenge_milestone",
            field=models.IntegerField(
                default=10000, help_text="Minimum steps milestone for challenges"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="platform_fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Platform fee percentage on challenge pools",
                max_digits=5,
            ),
        ),
    ]
