# Generated by Django 5.1.15 on 2026-09-23 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_systemsettings_challenge_milestones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_agent_ids',
            field=models.JSONField(blank=True, default=list, help_text='Staff user ids that take new tickets'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_auto_assign_mode',
            field=models.CharField(default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_category_assignees',
            field=models.JSONField(blank=True, default=dict, help_text='Ticket category -> staff user id'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_escalation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_escalation_raise_priority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_sla_high_hours',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_sla_low_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_sla_medium_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='support_sla_urgent_hours',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='SupportReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('general', 'General'), ('account', 'Account'), ('challenge', 'Challenge'), ('payment', 'Payment'), ('technical', 'Technical'), ('other', 'Other')], max_length=50)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_reply_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='admin_api.supporttag'),
        ),
    ]
