# Generated by Django 5.1.15 on 2026-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_support_desk_rules_and_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('ban', 'Ban'), ('unban', 'Unban'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('promote', 'Promote'), ('demote', 'Demote'), ('reset_password', 'Reset Password'), ('settings_change', 'Settings Change'), ('account_deleted', 'Account Deleted')], max_length=50),
        ),
    ]
