# Generated by Django 5.1.15 on 2026-09-24 09:50

from decimal import Decimal

from django.db import migrations, models


def keep_live_behaviour(apps, schema_editor):
    """These settings were stored but never enforced. Now that they are, rows
    still holding the old untouched defaults are moved to what the platform
    actually did (entry KES 50-10,000, no approval queue), so deploying this
    changes nothing for customers. Values an admin changed (audit log) stay."""
    SystemSettings = apps.get_model("admin_api", "SystemSettings")
    AuditLog = apps.get_model("admin_api", "AuditLog")

    def touched(field):
        return AuditLog.objects.filter(
            resource_type="settings", changes__has_key=field
        ).exists()

    for s in SystemSettings.objects.all():
        fields = []
        if (
            s.min_challenge_entry_fee == Decimal("1.00")
            and s.max_challenge_entry_fee == Decimal("1000.00")
            and not touched("min_challenge_entry_fee")
            and not touched("max_challenge_entry_fee")
        ):
            s.min_challenge_entry_fee = Decimal("50.00")
            s.max_challenge_entry_fee = Decimal("10000.00")
            fields += ["min_challenge_entry_fee", "max_challenge_entry_fee"]
        if s.challenge_approval_required and not touched("challenge_approval_required"):
            s.challenge_approval_required = False
            fields.append("challenge_approval_required")
        if fields:
            s.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_account_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='challenge_approval_required',
            field=models.BooleanField(default=False, help_text='New public challenges wait for admin approval before going live'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_challenge_entry_fee',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Maximum entry fee for new challenges (whole KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='min_challenge_entry_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum entry fee for new challenges (whole KES)', max_digits=10),
        ),
        migrations.RunPython(keep_live_behaviour, migrations.RunPython.noop),
    ]
