# Generated by Django 5.1.15 on 2026-09-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_settings_wiring_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='payout_hold_large_win_kes',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Payouts at or above this are held when the winner has open medium+ flags in the window', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='payout_hold_trust_score_max',
            field=models.PositiveIntegerField(default=60, help_text="Hold when the winner's trust score is at or below this (60 = REVIEW or worse)"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='payout_holds_enabled',
            field=models.BooleanField(default=True, help_text='Hold risky challenge payouts for staff review'),
        ),
    ]
