# Generated by Django 5.1.15 on 2026-09-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_settings_wiring_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=10)),
                ('last_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_result', models.CharField(blank=True, max_length=255)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled job state',
                'verbose_name_plural': 'Scheduled job states',
                'ordering': ['name'],
            },
        ),
    ]
