# Generated by Django 5.1.15 on 2026-09-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_payout_review_settings'),
        ('admin_api', '0008_scheduled_job_state'),
    ]

    operations = [
    ]
