# Generated by Django 5.1.15 on 2026-09-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0009_merge_scheduled_jobs_payout_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='device_integrity_policy',
            field=models.CharField(default='shadow', help_text="shadow = record only; enforce = failed devices' steps don't count toward challenges", max_length=10),
        ),
    ]
