# Generated by Django 5.1.15 on 2026-09-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0010_device_integrity_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='health_trusted_origins',
            field=models.TextField(blank=True, default='android  # This phone (Health Connect)\ncom.android.healthconnect.phone.*  # This phone (Health Connect)\ncom.sec.android.app.shealth  # Samsung Health\ncom.google.android.apps.fitness  # Google Fit\ncom.fitbit.FitbitMobile  # Fitbit\ncom.garmin.android.apps.connectmobile wearable  # Garmin Connect\ncom.xiaomi.wearable wearable  # Mi Fitness\ncom.huami.watch.hmwatchmanager wearable  # Zepp\ncom.xiaomi.hm.health wearable  # Zepp Life\ncom.huawei.health  # Huawei Health\ncom.strava  # Strava\ncom.apple.health.*  # Apple Health\ncom.strava.stravaride  # Strava\ncom.garmin.connect.mobile wearable  # Garmin Connect\ncom.huami.watch wearable  # Zepp\nHM.wristband wearable  # Zepp Life\ncom.xiaomi.miwatch.pro wearable  # Mi Fitness\ncom.huawei.iossporthealth  # Huawei Health\n', help_text='Trusted Health Connect / Apple Health apps, one per line'),
        ),
    ]
