# Generated by Django 5.1.15 on 2026-09-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0011_phase1c_health_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='drift_lookback_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drift_max_avg_abs_delta_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drift_max_high_drift_ratio_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drift_max_review_mismatch_ratio_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drift_min_samples',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='drift_per_sample_alert_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_daily_withdrawal_kes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_deposit_kes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_locked_balance_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_withdrawal_kes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_withdrawals_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_withdrawals_per_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_deposit_kes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_seconds_between_withdrawals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='paid_challenge_min_joined',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='paid_challenge_min_trust_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='play_integrity_accept_basic',
            field=models.BooleanField(blank=True, help_text='Accept MEETS_BASIC_INTEGRITY phones as verified (blank = server value)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='rank_payouts_enabled',
            field=models.BooleanField(blank=True, help_text='Winner-takes-all / top-3 challenges (blank = server RANK_PAYOUTS_ENABLED)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='recon_max_callback_failure_rate_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='recon_max_negative_balance_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='recon_max_stuck_processing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='recon_max_unprocessed_callbacks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='risk_ml_hold_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='step_evidence_cutover_date',
            field=models.DateField(blank=True, help_text='Days before this keep full challenge credit (blank = server value)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='step_money_requires_evidence',
            field=models.BooleanField(blank=True, help_text='Only evidence-backed steps count toward challenge money (blank = server value)', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('ban', 'Ban'), ('unban', 'Unban'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('promote', 'Promote'), ('demote', 'Demote'), ('reset_password', 'Reset Password'), ('settings_change', 'Settings Change'), ('account_deleted', 'Account Deleted'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('archive', 'Archive'), ('restore', 'Restore'), ('retire', 'Retire'), ('activate', 'Activate'), ('hide', 'Hide'), ('unhide', 'Unhide'), ('merge', 'Merge'), ('bulk_update', 'Bulk update'), ('pause', 'Pause'), ('resume', 'Resume'), ('retry', 'Retry'), ('run_job', 'Run job'), ('remove_member', 'Remove member'), ('transfer_ownership', 'Transfer ownership'), ('reorder', 'Reorder')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('user', 'User'), ('challenge', 'Challenge'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('badge', 'Badge'), ('settings', 'System Settings'), ('support', 'Support'), ('auth', 'Authentication'), ('system', 'System'), ('team', 'Team'), ('support_tag', 'Support tag'), ('support_template', 'Support saved reply'), ('announcement', 'Announcement'), ('faq_category', 'Help category'), ('faq_article', 'Help article'), ('legal_document', 'Legal document'), ('anticheat_policy', 'Anti-cheat policy'), ('feed_event', 'Feed item'), ('challenge_message', 'Challenge chat message'), ('social_report', 'Social report'), ('risk_model', 'Risk model'), ('scheduled_job', 'Scheduled job'), ('data_export', 'Data export')], max_length=50),
        ),
    ]
