# Generated by Django 5.1.15 on 2026-09-30 09:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

# Every role except owner (apps/admin_api/roles.py DEFAULT_LEGACY_ROLES), written out
# here so the migration never changes when the role catalogue does.
LEGACY_ROLES = ["finance", "support", "trust", "content", "settings"]


def give_existing_staff_roles(apps, schema_editor):
    """Existing staff keep working: every non-superuser staff account gets an explicit
    profile with all roles except owner. Superusers are owners and need no row."""
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    StaffProfile = apps.get_model("admin_api", "StaffProfile")
    for user_id in User.objects.filter(is_staff=True, is_superuser=False).values_list("id", flat=True):
        StaffProfile.objects.get_or_create(user_id=user_id, defaults={"roles": list(LEGACY_ROLES)})


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0011_phase1c_health_sources'),
        ('wallet', '0003_wallet_corrections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('ban', 'Ban'), ('unban', 'Unban'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('promote', 'Promote'), ('demote', 'Demote'), ('reset_password', 'Reset Password'), ('settings_change', 'Settings Change'), ('account_deleted', 'Account Deleted'), ('invite', 'Invite'), ('roles_change', 'Roles Change'), ('adjust', 'Adjust'), ('reverse', 'Reverse'), ('resolve', 'Resolve'), ('export', 'Export'), ('sign_out', 'Sign Out Everywhere'), ('unlock', 'Unlock'), ('device_reset', 'Device Reset'), ('steps_correction', 'Steps Correction'), ('xp_adjust', 'XP Adjust'), ('award', 'Award'), ('revoke', 'Revoke'), ('message', 'Message'), ('disqualify', 'Disqualify'), ('archive', 'Archive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('user', 'User'), ('challenge', 'Challenge'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('badge', 'Badge'), ('settings', 'System Settings'), ('support', 'Support'), ('auth', 'Authentication'), ('staff', 'Staff'), ('deposit', 'Deposit'), ('wallet', 'Wallet'), ('steps', 'Steps')], max_length=50),
        ),
        migrations.CreateModel(
            name='ConsoleControls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_approval_threshold_kes', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('roles', models.JSONField(default=list)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('code_hint', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('needs_second_approval', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('applied_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='wallet.wallettransaction')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='wallet.wallettransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='adm_wcorr_user_idx')],
            },
        ),
        migrations.RunPython(give_existing_staff_roles, migrations.RunPython.noop),
    ]
