# Generated by Django 5.1.15 on 2026-09-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_console_business_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledjobstate',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scheduledjobstate',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledjobstate',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledjobstate',
            name='paused_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('trigger', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['name', '-started_at'], name='admin_api_s_name_7e14d8_idx')],
            },
        ),
    ]
