# Generated by Django 5.1.15 on 2026-09-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_staff_roles_and_money_controls'),
        ('admin_api', '0013_scheduled_job_pause_and_runs'),
    ]

    operations = [
    ]
