# Generated by Django 5.1.15 on 2026-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0014_merge_20260930_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('ban', 'Ban'), ('unban', 'Unban'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('promote', 'Promote'), ('demote', 'Demote'), ('reset_password', 'Reset Password'), ('settings_change', 'Settings Change'), ('account_deleted', 'Account Deleted'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('archive', 'Archive'), ('restore', 'Restore'), ('retire', 'Retire'), ('activate', 'Activate'), ('hide', 'Hide'), ('unhide', 'Unhide'), ('merge', 'Merge'), ('bulk_update', 'Bulk update'), ('pause', 'Pause'), ('resume', 'Resume'), ('retry', 'Retry'), ('run_job', 'Run job'), ('remove_member', 'Remove member'), ('transfer_ownership', 'Transfer ownership'), ('reorder', 'Reorder'), ('invite', 'Invite'), ('roles_change', 'Roles Change'), ('adjust', 'Adjust'), ('reverse', 'Reverse'), ('resolve', 'Resolve'), ('export', 'Export'), ('sign_out', 'Sign Out Everywhere'), ('unlock', 'Unlock'), ('device_reset', 'Device Reset'), ('steps_correction', 'Steps Correction'), ('xp_adjust', 'XP Adjust'), ('award', 'Award'), ('revoke', 'Revoke'), ('message', 'Message'), ('disqualify', 'Disqualify')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('user', 'User'), ('challenge', 'Challenge'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('badge', 'Badge'), ('settings', 'System Settings'), ('support', 'Support'), ('auth', 'Authentication'), ('system', 'System'), ('team', 'Team'), ('support_tag', 'Support tag'), ('support_template', 'Support saved reply'), ('announcement', 'Announcement'), ('faq_category', 'Help category'), ('faq_article', 'Help article'), ('legal_document', 'Legal document'), ('anticheat_policy', 'Anti-cheat policy'), ('feed_event', 'Feed item'), ('challenge_message', 'Challenge chat message'), ('social_report', 'Social report'), ('risk_model', 'Risk model'), ('scheduled_job', 'Scheduled job'), ('data_export', 'Data export'), ('staff', 'Staff'), ('deposit', 'Deposit'), ('wallet', 'Wallet'), ('steps', 'Steps')], max_length=50),
        ),
    ]
