# Generated by Django 5.0.2 on 2026-03-01 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon name', max_length=10)),
                ('badge_type', models.CharField(choices=[('milestone', 'Milestone'), ('achievement', 'Achievement'), ('challenge', 'Challenge'), ('streak', 'Streak'), ('rank', 'Rank')], default='achievement', max_length=20)),
                ('color', models.CharField(default='#00F5E9', help_text='Hex color code', max_length=7)),
                ('criteria_type', models.CharField(choices=[('first_challenge', 'First Challenge Joined'), ('first_win', 'First Challenge Won'), ('step_milestone', 'Step Milestone'), ('challenge_wins', 'Number of Challenge Wins'), ('streak_days', 'Streak Days'), ('total_xp', 'Total XP Earned'), ('manual', 'Manual Award')], default='manual', max_length=50)),
                ('criteria_value', models.IntegerField(blank=True, help_text='Threshold value for criteria', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='gamificatio_slug_e8a164_idx'), models.Index(fields=['criteria_type'], name='gamificatio_criteri_33b962_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyLoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('total_logins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Login Streak',
                'verbose_name_plural': 'Daily Login Streaks',
            },
        ),
        migrations.CreateModel(
            name='LevelMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('reached_at', models.DateTimeField(auto_now_add=True)),
                ('total_xp', models.IntegerField()),
                ('reward_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level Milestone',
                'verbose_name_plural': 'Level Milestones',
                'ordering': ['-level'],
                'indexes': [models.Index(fields=['user', 'level'], name='gamificatio_user_id_ee482c_idx'), models.Index(fields=['level'], name='gamificatio_level_108b61_idx')],
                'unique_together': {('user', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True, help_text='Shows notification until user views')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'earned_at'], name='gamificatio_user_id_683edb_idx'), models.Index(fields=['badge'], name='gamificatio_badge_i_20a089_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('daily_login', 'Daily Login'), ('challenge_join', 'Challenge Join'), ('challenge_complete', 'Challenge Complete'), ('challenge_win', 'Challenge Win'), ('step_milestone', 'Step Milestone'), ('streak_milestone', 'Streak Milestone'), ('level_up', 'Level Up'), ('manual_award', 'Manual Award'), ('admin_adjustment', 'Admin Adjustment')], max_length=30)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(-10000)])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Event',
                'verbose_name_plural': 'XP Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_a78f12_idx'), models.Index(fields=['event_type', 'created_at'], name='gamificatio_event_t_793b8a_idx'), models.Index(fields=['processed', 'created_at'], name='gamificatio_process_349e12_idx')],
            },
        ),
    ]
