# Generated by Django 5.1.15 on 2026-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpevent',
            name='event_type',
            field=models.CharField(choices=[('daily_login', 'Daily Login'), ('challenge_join', 'Challenge Join'), ('challenge_complete', 'Challenge Complete'), ('challenge_win', 'Challenge Win'), ('step_milestone', 'Step Milestone'), ('daily_steps', 'Daily Steps'), ('daily_goal', 'Daily Goal Reached'), ('streak_milestone', 'Streak Milestone'), ('level_up', 'Level Up'), ('manual_award', 'Manual Award'), ('admin_adjustment', 'Admin Adjustment')], max_length=30),
        ),
    ]
