# Generated by Django 5.1.15 on 2026-09-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_xp_step_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='is_retired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levelmilestone',
            name='reward_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gamification.badge'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='gamification.badge'),
        ),
    ]
