# Generated by Django 5.0 on 2026-03-08 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('raw_payload', models.JSONField()),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('payout', 'Challenge Payout'), ('refund', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('tracking_reference', models.CharField(max_length=100, unique=True)),
                ('collection_id', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_reference', models.CharField(blank=True, max_length=100)),
                ('fail_reason', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('narration', models.CharField(max_length=255)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_3e0999_idx'), models.Index(fields=['order_id'], name='payments_pa_order_i_d65105_idx'), models.Index(fields=['tracking_reference'], name='payments_pa_trackin_e7a30a_idx'), models.Index(fields=['status', 'type'], name='payments_pa_status_138ec8_idx'), models.Index(fields=['mpesa_reference'], name='payments_pa_mpesa_r_84c67e_idx')],
            },
        ),
    ]
