# Generated by Django 5.0 on 2026-03-08 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Admin Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=20)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa Mobile'), ('bank', 'Bank Account'), ('paybill', 'Paybill / Till')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('bank_code', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('is_paybill', models.BooleanField(default=True)),
                ('tracking_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_reference', models.CharField(blank=True, max_length=100)),
                ('fail_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_wi_user_id_b01cbe_idx'), models.Index(fields=['status', '-created_at'], name='payments_wi_status_be2ac6_idx'), models.Index(fields=['tracking_reference'], name='payments_wi_trackin_3f3470_idx')],
            },
        ),
    ]
