# Generated by Django 5.1.15 on 2026-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenttransaction_wallet_transaction_platformrevenue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformrevenue',
            new_name='payments_pl_collect_a46a18_idx',
            old_name='payments_pl_collecte_abc123_idx',
        ),
    ]
