# Generated by Django 5.0 on 2026-03-09 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_and_conditions', 'Terms and Conditions'), ('cookie_policy', 'Cookie Policy'), ('refund_policy', 'Refund Policy'), ('other', 'Other')], help_text='Each document type has exactly one published version at a time.', max_length=30, unique=True)),
                ('title', models.CharField(help_text='Display title shown to users. e.g. "Privacy Policy"', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug. Auto-generated from title. e.g. "privacy-policy"', max_length=100, unique=True)),
                ('content_html', models.TextField(blank=True, help_text='Full document content as HTML. Rendered in the mobile app.')),
                ('uploaded_file', models.FileField(blank=True, help_text='Original DOCX or PDF file. Stored for download and as source of truth.', null=True, upload_to='legal/files/')),
                ('file_type', models.CharField(blank=True, help_text='docx / pdf / html — auto-detected from upload', max_length=10)),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-incremented each time the document is published.')),
                ('version_label', models.CharField(blank=True, help_text='Human-readable version e.g. "1.2". Auto-generated as "1.{version}"', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('notify_users', models.BooleanField(default=False, help_text='If True, mobile app shows "Updated" badge to users who have not re-read this version.')),
                ('change_summary', models.CharField(blank=True, help_text='Optional: brief description of what changed in this version. Shown to users in the update notification.', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_legal_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('version_label', models.CharField(max_length=20)),
                ('content_html', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='legal.legaldocument')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('document', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserDocumentAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_seen', models.PositiveIntegerField()),
                ('acknowledged_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_acks', to='legal.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document')},
            },
        ),
    ]
