# Generated by Django 5.1.15 on 2026-09-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='draft_html',
            field=models.TextField(blank=True, default='', help_text='Unpublished edits. Admin saves land here; publishing copies them into content_html. Empty means no pending changes.'),
        ),
    ]
