# Generated by Django 5.1.15 on 2026-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_legaldocument_draft_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_and_conditions', 'Terms and Conditions'), ('cookie_policy', 'Cookie Policy'), ('refund_policy', 'Refund Policy'), ('fair_play_rules', 'Fair Play and Payout Review Rules'), ('other', 'Other')], help_text='Each document type has exactly one published version at a time.', max_length=30, unique=True),
        ),
    ]
